### ISSUE TITLE
PG::UndefinedFunction: ERROR:  function max(uuid)

### ISSUE THREAD

**Issue by brentgreeff** [blocknotes/active_storage_db#28]
```log
+ ./bin/rails asdb:list
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function max(uuid) does not exist
LINE 1: SELECT MAX("active_storage_blobs"."id") FROM "active_storage...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

This seems to be working well with ActionMailbox - active_storage_db_files has a single record - with a size that makes sense for an email's content + the attachment size. - and I can view the email here - http://localhost:3000/rails/conductor/action_mailbox/inbound_emails

but `./bin/rails asdb:list` produces the error above.

Can I ignore this? - has this been designed with non-uuids in mind?

Going to deploy to render.com - where it will either pass or fail - but seems to work.

**Comment by blocknotes** [comment]
Hey @brentgreeff
Sorry for the very late reply 😓 
I haven't a project with uuid primary keys, but I'll make some tests.
In the meanwhile, I started a PR to handle the issue: https://github.com/blocknotes/active_storage_db/pull/33

**Comment by blocknotes** [comment]
I'm closing this one because it should be solved.
Feel free to reopen it if needed.
