### ISSUE TITLE
Support for Rails 5.2

### ISSUE THREAD

**Issue by henkesn** [blocknotes/active_storage_db#4]
Hey guys,

at first good to see things keep moving using the db as active storage backend after having a look on alternative projects. This looks like to the best version around.
Just one question, is there a reason why the gemspec requires rails 6.0? I'm just playing around a bit and it seems to work with 5.2, too. After setting rails and active storage to 5.2 there were no failures for the mysql specs. I haven't tested postgres. I will now go on and check if there are issues arising with 5.2 in development.

**Comment by blocknotes** [comment]
Hey @henkesn.
I saw your PR to permit to use Rails 5.2.x but when I tried to run the specs I got some errors (that could be related to the ActiveStorage version), I replied in the PR too. At the moment, I haven't the resources to make some investigation to support Rails 5.

**Comment by henkesn** [comment]
Closed with #5.
